# Generated by Django 4.2.7 on 2024-01-03 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_rename_user_msg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msg',
            old_name='namesage',
            new_name='message',
        ),
    ]
